name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build dependencies
      run: |
        git clone https://github.com/xmdhs/player
        cd player
        npm install
        npm run build
        mkdir ../frontend
        cp -r dist/ ../frontend/

    - name: Build
      run: |
        go install github.com/wailsapp/wails/v2/cmd/wails@latest
        
        wails build -trimpath -ldflags="-w -s" -o bin/player-linux -upx	
        wails build -trimpath -ldflags="-w -s" -o bin/player-windows.exe -platform windows/amd64 -upx	

    - name: Test
      run: go test -race -v ./...

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
          # A file, directory or wildcard pattern that describes what to upload
          path: bin/player-*
          name: ${{ github.run_number }}
